// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zOis5XbF9XVOa3ilvUe8lgLFsod0hPM',
    appId: '1:74536732333:web:e1af236e3e652e8645a824',
    messagingSenderId: '74536732333',
    projectId: 'myapp-b61a0',
    authDomain: 'myapp-b61a0.firebaseapp.com',
    storageBucket: 'myapp-b61a0.appspot.com',
    measurementId: 'G-SQXHJYWDP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwk3irg5lgdEa207RaqA8RquYWVfufQ-I',
    appId: '1:74536732333:android:681e82e8939925eb45a824',
    messagingSenderId: '74536732333',
    projectId: 'myapp-b61a0',
    storageBucket: 'myapp-b61a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vAE0GZLKWUn_a7LENRDs35mL9z1xKbM',
    appId: '1:74536732333:ios:460dedc4881e43a345a824',
    messagingSenderId: '74536732333',
    projectId: 'myapp-b61a0',
    storageBucket: 'myapp-b61a0.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5vAE0GZLKWUn_a7LENRDs35mL9z1xKbM',
    appId: '1:74536732333:ios:abcb82bfd23f470045a824',
    messagingSenderId: '74536732333',
    projectId: 'myapp-b61a0',
    storageBucket: 'myapp-b61a0.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
